#!/usr/bin/env ruby
begin
  require 'autotest/growl'
  require 'autotest/fsevent'
  Autotest::Growl::remote_notification = true
rescue LoadError
  puts "gem install autotest-growl; gem install autotest-fsevent"
end

Autotest.add_hook :initialize do |autotest|
  %w{.git .svn .hg .DS_Store ._* vendor}.each {|exception| autotest.add_exception(exception) }
  false
end

