#!/usr/bin/ruby
require 'autotest/growl'
require 'autotest/fsevent'

Autotest::Growl::remote_notification = true
Autotest.add_hook :initialize do |autotest|
  %w{.git .svn .hg .DS_Store ._* vendor}.each {|exception| autotest.add_exception(exception) }
  false
end
